#!/bin/bash
#
#  nspawn-renew-root-password - renew root password for a container
#
#  Copyright (C) 2017, 2018, 2019, 2021 Alexander Yermolenko
#  <yaa.mbox@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

droot=${1:?Container directory is required}
#droot="/srv/nspawn/my-debian-container"

distro_arch="amd64"

die()
{
    msg=${1:-"Unknown Error"}
    echo "ERROR: $msg" 1>&2
    exit 1
}

goodbye()
{
    msg=${1:-"Cancelled by user"}
    echo "INFO: $msg" 1>&2
    exit 1
}

info()
{
    msg=${1:-"Info"}
    echo "INFO: $msg" 1>&2
}

require()
{
    local cmd=${1:?"Command name is required"}
    local extra_info=${2:+"\nNote: $2"}
    hash $cmd 2>/dev/null || die "$cmd not found$extra_info"
}

common_nspawn_options=""

personality="x86-64"
[ "$distro_arch" == "i386" ] && personality="x86"
[ "$distro_arch" == "x86" ] && personality="x86"
common_nspawn_options="$common_nspawn_options --personality=$personality"

echo "droot=$droot"
echo "common_nspawn_options=$common_nspawn_options"

[ "$EUID" -eq 0 ] || die "Superuser privileges required"

require pwgen

password=`pwgen --secure 15`

systemd_version=$( systemd-nspawn --version | awk 'FNR==1 {print $2}' )
echo "systemd-nspawn version: $systemd_version"

if [ $systemd_version -gt 241 ]
then
    echo "root:$password" | systemd-nspawn $common_nspawn_options -D "$droot" --pipe chpasswd \
        || die "Cannot set root password"
else
    echo "root:$password" | systemd-nspawn $common_nspawn_options -D "$droot" chpasswd \
        || die "Cannot set root password"
fi

echo "New root password for $droot: $password"

passwd_log=nspawn.passwd.log
echo "$droot: $password" >> "$passwd_log"
chown root:root "$passwd_log"
chmod 600 "$passwd_log"
