#!/bin/bash
#
#  nspawn-run-shell - run shell inside a container
#
#  Copyright (C) 2021 Alexander Yermolenko <yaa.mbox@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

machine_name=${1:?Container name is required}
user=${2:-root}

machinectl shell "$user@$machine_name" /bin/bash
# machinectl shell "root@$machine_name" /bin/su - $user
# --machine="$machine_name"
